# Generated by Django 2.2.18 on 2021-02-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workCk', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='work_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
