# Generated by Django 2.2.18 on 2021-02-17 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workCk', '0004_auto_20210218_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_Nmae',
        ),
        migrations.AddField(
            model_name='work',
            name='work_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
