# Generated by Django 2.2.18 on 2021-02-19 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workCk', '0005_auto_20210218_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='work_num',
            new_name='bussiness_num',
        ),
        migrations.AddField(
            model_name='work',
            name='worker_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
