# Generated by Django 2.2.18 on 2021-02-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workCk', '0006_auto_20210219_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='worker_num',
            new_name='work_num',
        ),
    ]
